# Generated by Django 4.2 on 2023-04-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=64)),
                ('number_of_room', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=8)),
                ('college', models.CharField(max_length=32)),
                ('room_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('node', models.CharField(blank=True, max_length=2, null=True)),
                ('antennaStatus', models.CharField(blank=True, max_length=32, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systems.student')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('person_id', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.room')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('property_number', models.CharField(max_length=64)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.room')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32)),
                ('property_number', models.CharField(max_length=64)),
                ('ID_IT', models.CharField(max_length=32)),
                ('mb', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('power', models.CharField(blank=True, max_length=32, null=True)),
                ('ssd', models.CharField(blank=True, max_length=32, null=True)),
                ('ssdM2', models.CharField(blank=True, max_length=32, null=True)),
                ('hdd', models.CharField(blank=True, max_length=32, null=True)),
                ('dvd', models.CharField(blank=True, max_length=32, null=True)),
                ('vga', models.CharField(blank=True, max_length=32, null=True)),
                ('os', models.CharField(max_length=10)),
                ('soft', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.room')),
            ],
        ),
    ]
