# Generated by Django 4.1.7 on 2023-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=32)),
                ('property_number', models.CharField(max_length=64)),
                ('ID_IT', models.CharField(max_length=32)),
                ('mb', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('power', models.CharField(blank=True, max_length=32, null=True)),
                ('ssd', models.CharField(blank=True, max_length=32, null=True)),
                ('ssdM2', models.CharField(blank=True, max_length=32, null=True)),
                ('hdd', models.CharField(blank=True, max_length=32, null=True)),
                ('dvd', models.CharField(blank=True, max_length=32, null=True)),
                ('vga', models.CharField(blank=True, max_length=32, null=True)),
                ('os', models.CharField(max_length=10)),
                ('software', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('property_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('code_meli', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=8)),
                ('college', models.CharField(max_length=32)),
                ('room_tell', models.CharField(blank=True, max_length=32, null=True)),
                ('node', models.CharField(blank=True, max_length=2, null=True)),
                ('antenna', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
