# Generated by Django 4.1.7 on 2023-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=32)),
                ('roomNumber', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=32)),
                ('propertyNum', models.CharField(max_length=64)),
                ('idIt', models.CharField(max_length=32)),
                ('mb', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('power', models.CharField(blank=True, max_length=32, null=True)),
                ('ssd', models.CharField(blank=True, max_length=32, null=True)),
                ('ssdM2', models.CharField(blank=True, max_length=32, null=True)),
                ('hdd', models.CharField(blank=True, max_length=32, null=True)),
                ('dvd', models.CharField(blank=True, max_length=32, null=True)),
                ('vga', models.CharField(blank=True, max_length=32, null=True)),
                ('os', models.CharField(max_length=10)),
                ('soft', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=32)),
                ('roomNumber', models.CharField(max_length=8)),
                ('deviceName', models.CharField(max_length=32)),
                ('deviceModel', models.CharField(max_length=32)),
                ('deviceID', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=32)),
                ('roomNumber', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('family', models.CharField(max_length=32)),
                ('personId', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('roomNumber', models.CharField(max_length=8)),
                ('college', models.CharField(max_length=32)),
                ('roomTel', models.CharField(blank=True, max_length=32, null=True)),
                ('node', models.CharField(blank=True, max_length=2, null=True)),
                ('antennaStatus', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
